### ISSUE TITLE
Calculate Adult Male Equivalent dynamically

### ISSUE THREAD

**Issue by rbroth** [micronutrientsupport/database-architecture#13]
We will store the Adult Male equivalent provided by the dataset. However, if no AME is given, we want to calculate our own from other data such as age, sex, lactation, etc.

- What variables are needed to calculate the AME?
- What is the formula/code/IFTHEN statements for calculating the AME?

**Comment by kmtang** [comment]
Hi Roman,
AME is calculated by integrating data/ assumptions about each household member's age, sex, weight, physical activity level, pregnancy status, and lactation status. This only applies to food consumption data that is reported at the household level (i.e. not data about national supply, or the individual level). These factor values will be calculated by me first for the pre-baked values. Will you need a way of integrating this into the BYO data feature?

**Comment by kmtang** [comment]
As for a formula, 
AME (for an individual household member) = a / b; where: 
a = energy requirement of household member X
b = energy requirement of an adult male

Assuming constant body weight and physical activity level: 

a =  e + p + l; where
e = individual member's daily energy requirement adjusted for age & sex (see attached table)
[ame_factors.csv.zip](https://github.com/micronutrientsupport/bmgf-maps/files/5400207/ame_factors.csv.zip)
p = additional energy required for pregnancy
l = additional energy required for lactation

b = constant (since energy requirement for an adult male will not change)

Finally, after all that, to calculate to household's AME, we sum the individual AMEs of everyone in the household. This will be done for every household in the dataset. I don't do this individually for each one obviously, I just run a script I write in R that does it for the full dataset. Would you try and integrate this feature into the BYO data feature of the tool?

**Comment by rbroth** [comment]
That makes sense. The formula you give for calculating AME would be easy to implement in the system, so calculating AME from BYOD shouldn't be a problem (assuming, however, that age, sex, pregnancy, and lactation are provided). 

Why does AME not apply to food consumption data that is reported at the individual level? I would assume that it would be just as easy to calculate AME when you're asking an individual about their food intake as when you're asking a household?

**Comment by bgsandan** [comment]
Closing for now.  Will re-open/re-issue if/when appropriate given BYOD requirements
