### ISSUE TITLE
Add columns to Household_Member table

### ISSUE THREAD

**Issue by andy-bevan** [micronutrientsupport/database-architecture#172]
Looks like we need:

- Literacy (as well as education level)
- BMI

Remember to update the format specifications.

Related to issue #142

**Comment by andy-bevan** [comment]
Yes I would keep BMI. However, you can calculate easily from weight and height so you might want to ask the tool to do that rather than to import it.

Fanny (via email)

**Comment by andy-bevan** [comment]
Just noticed that the LITERACY field is still coded. Can you translate those values for us, please? - Andy

I don’t have the corresponding codes for now so I would suggest to ignore that variable for the moment.

Fanny (via email)

**Comment by andy-bevan** [comment]
Literacy has now been decoded in the latest dataset for Ethiopia WRA sent by Fanny via email.

**Comment by andy-bevan** [comment]
@rbroth question about attribution:

Shouldn't 'interview_date' be an attribute of either household_member or biomarker_measurement rather than household?
The reason I ask is because there may be > 1 interview per household.

**Comment by rbroth** [comment]
> there may be > 1 interview per household.

is that confirmed? I was under the impression that a survey only went to each household once to collect data. If so, we may need to have a think about this, because we may end up with lots of entries confirming "Ah yes, you this person still has the same sex as at the last interview". 

That said, I think HHM is a better place than biomarker_measurement, because we already have date_sampled on biomarker measurement.

**Comment by andy-bevan** [comment]
Its confirmed by the data. And its causing me a problem because we have the same 'household id' for multiple people/interviews but with slightly different lat/lon or alt. The way we are inserting the data at the moment means that when this happens, we are duplicating the data for those household members.
