### ISSUE TITLE
FCT priority

### ISSUE THREAD

**Issue by rbroth** [micronutrientsupport/database-architecture#19]
How should Food Composition Tables be prioritized?

Currently, we are assuming that each FCT will an "area of validiy" e.g. the Malawi FCT has an area that covers the country of Malawi; another FCT might have been made for Sudan in 2005 and thus cover modern Sudan and South Sudan.

When a user wants to know the most relevant FCT, the

For a given geographic point, the current function find all FCTs that overlap that point, then orders them by 
1) Manually set priority (currently NULL, let me know if you guys have an order in mind) 
2) Geometric area (smaller is assumed to be more relevant)
3) publication date (newer is considered more relevant)

If no FCT areas overlap, the order is
1) Distance from the point to the  nearest FCT area border (nearer is considered more relevant)
2) Manually set priority (currently NULL)
3) Publication date

**Comment by LuciaSegovia** [comment]
I think that priotirization is ok for now. I will add a quality attribute (or is that considerered as 'Manually set priority'?). 

Also, there are some FCTs for some countries that we are not going to use due to quality issues. But, it can happen that in the (near) future, they release a newer version that it is valid. 

How easy or difficult is it to change the priotity in the future?

**Comment by LuciaSegovia** [comment]
Then, I don't think it is an issue. I am not sure yet on how to integrate the quality of the FCT into the priority, tbh...

**Comment by spenny-liam** [comment]
@LuciaSegovia Do you have any values for manual priorities for FCT's being used? Currently for a given location or area the FCT's returned will be prioritised in the order of:
- Whether the FCT area contain or overlap with the given geometry
- The distance between the geometry and the FCT area
- The size of the FCT area
- The publication date
This will most likely result in them being prioritised by distance all of the time, as there is very little chance of two distances being the same and it needing to be decided by the next variables.

**Comment by LuciaSegovia** [comment]
@spenny-liam I think overall it is what we agreed. The other consideration will be if for certain items, it is better to find a similar food item in the same geometry than to take it from the next closest geometry. For example, if we do not have selenium data for maize in Malawi, to use selenium data in wheat in Malawi instead of selenium data for maize in Kenya. But, I do not know if that is "realistic" to implement. 

> @LuciaSegovia Do you have any values for manual priorities for FCT's being used?

Also, sorry but I did not understand what you mean by that

**Comment by spenny-liam** [comment]
> > @LuciaSegovia Do you have any values for manual priorities for FCT's being used?
> 
> Also, sorry but I did not understand what you mean by that

In the chats above and in other chats there is mention of a priority/quality column on the fct source/metadata that indicates whether we want to use it more instead of other FCT’s. I think we can probably leave this until we notice any issues with the data being returned. It all looks sensible for now.

**Comment by LuciaSegovia** [comment]
@spenny-liam Ok, I know what you mean now :) Yes, I think we can leave it for the future since we have very few FCT at the moment and they are all, more or less of the same quality. Thanks!
