### ISSUE TITLE
Unpick country_id in country_consumption table and child views

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/database-architecture#217]
`country_consumption` includes a country\_id field which is currently unpopulated.  The data\_source\_id field references the `country_consumption_source` table which has a geometry.

The country\_id field is probably unnecessary.  Views such as the top20\_mn\_per\_country view should probably use a spatial query to get the country\_id as in some of the other views

**Comment by rbroth** [comment]
Would it be worth to rework the country_consumption table as a view, if we're going to calculate the consumption from one or more datasets per country?
Also, aren't the geometries for the FAO datasets just the borders of the country?

**Comment by rbroth** [comment]
In fact, looking at the country_consumption_source table, it probably makes more sense to replace the geometry column with a country_id column, or even replace it entirely, since either the source will have data for a specific country (e.g. "Roman's 2011 Malawi Food Consumption Report: Now with Aquatic Animals!") or it will cover multiple countries and the geometry of the areas it covers won't be suitable for doing joins (e.g. "Roman's Big Book of Food Consumption of Asian Countries 2017: Now includes Turkmenistan!"

**Comment by andy-bevan** [comment]
So now the plan is:

- [ ] Remove geometry column from country_consumption_source 
- [ ] Change the top20_mn_per_country view back to how it was
- [ ] Reinstate country_id column in country_consumption table
- [ ] Populate that column with an id when loading the data

Is this correct @rbroth?

**Comment by rbroth** [comment]
Let's discuss with @bgsandan in the standup

**Comment by andy-bevan** [comment]
@rbroth do you remember if we have a decision on this?

**Comment by rbroth** [comment]
No idea. @bgsandan, how does that sound?

**Comment by andy-bevan** [comment]
Just noticed that this issue is the subject of a pull request:

https://github.com/micronutrientsupport/database-architecture/pull/297

Which ground to a halt? @rbroth

**Comment by bgsandan** [comment]
Happy with the implementation in the open PR I think.  We can keep an eye out for any perf issues / other optimisation opportunities once we have everything else working™.  @andy-bevan I've approved the PR so feel free to merge and close this issue at your leisure
