### ISSUE TITLE
biomarker_summary view not reporting all surveys

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/database-architecture#219]
Need to check the `biomarker_summary` view.  This is the view that feeds the data into the R script. 

It seems to currently return data for the Malawi survey but doesn't seem to be including the data from the Ethiopia survey (ID 3). It may be that key metadata fields (geometry, type etc.) are missing in the data causing it not to pull through

**Comment by andy-bevan** [comment]
@bgsandan I'm looking at this and it seems to me that the complex 'where' clauses being used to fetch the group_id could be made to work for existing data but may fail if new groups are introduced. Since we know the group id at source, I suggest we mandate its inclusion in the file and add it to the household member table and store it there?

**Comment by andy-bevan** [comment]
Its looks like we are not even getting the household location (lat and lon) in our Malawi file.

**Comment by bgsandan** [comment]
> @bgsandan I'm looking at this and it seems to me that the complex 'where' clauses being used to fetch the group_id could be made to work for existing data but may fail if new groups are introduced. Since we know the group id at source, I suggest we mandate its inclusion in the file and add it to the household member table and store it there?

Yeh, that could certainly work and would reduce the complexity and fragility of this view

**Comment by andy-bevan** [comment]
> Its looks like we are not even getting the household location (lat and lon) in our Malawi file.

I've asked Fanny to include the lat lon in the Malawi data, if available...

**Comment by andy-bevan** [comment]
Something I have found with this view is that each household will have 3 levels of area aggregation. 

This is because the query joins to the aggregation_area table based on whether the point location of the household is within the aggregation area - and as they are nested to 3 levels, this will return 3 areas.  

Is this what is expected?

**Comment by bgsandan** [comment]
Should now be resolved
