### ISSUE TITLE
Have both folic acid and folate

### ISSUE THREAD

**Issue by rbroth** [micronutrientsupport/database-architecture#47]
Folic acid is a food additive used to add folate to foods.

**Comment by LuciaSegovia** [comment]
Please see #40

**Comment by rbroth** [comment]
Yes, but we will store folate for all other FCt, will we not? Ergo, I need to change the column name in the database

**Comment by LuciaSegovia** [comment]
But it could be that some FCTs, we have information on folic acid too. Moreover, it is important for fortification. So, if possible, I would recomend to 1) change the name for Malawi FCT to folate, 2) keep folic acid as variable.

**Comment by rbroth** [comment]
So we actually want both Folic acid _and_ Folate?

**Comment by LuciaSegovia** [comment]
Yes

**Comment by LuciaSegovia** [comment]
I see your point. We need to report only folate for calculating deficiencies. But, the reason of keeping both it is because: 1) you may want to know the amount of folic acid for different fortification scenarios, 2) the activity of folic acid (the synthetic one) is higher that food folate. This means that 1mg of folic acid is not equal to 1mg of folate. So, the way it is done in some fct is that you have dietary folate equivalents (as the sum of both food folate and folic acid) plus the two other variables.
